package com.citi.portfoliomanager.entity;

public class Constant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_constant.constant_key
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private String constantKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_constant.constant_value
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private String constantValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_constant.constant_key
     *
     * @return the value of pm_constant.constant_key
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public String getConstantKey() {
        return constantKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_constant.constant_key
     *
     * @param constantKey the value for pm_constant.constant_key
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setConstantKey(String constantKey) {
        this.constantKey = constantKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_constant.constant_value
     *
     * @return the value of pm_constant.constant_value
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public String getConstantValue() {
        return constantValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_constant.constant_value
     *
     * @param constantValue the value for pm_constant.constant_value
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setConstantValue(String constantValue) {
        this.constantValue = constantValue;
    }
}