package com.citi.portfoliomanager.entity;

import java.math.BigDecimal;
import java.util.Date;

public class PortfolioHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_portfolio_history.portfolio_history_id
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    private Integer portfolioHistoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_portfolio_history.profolio_id
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    private Integer profolioId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_portfolio_history.cal_date
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    private Date calDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_portfolio_history.total_assert
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    private BigDecimal totalAssert;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_portfolio_history.portfolio_history_id
     *
     * @return the value of pm_portfolio_history.portfolio_history_id
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    public Integer getPortfolioHistoryId() {
        return portfolioHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_portfolio_history.portfolio_history_id
     *
     * @param portfolioHistoryId the value for pm_portfolio_history.portfolio_history_id
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    public void setPortfolioHistoryId(Integer portfolioHistoryId) {
        this.portfolioHistoryId = portfolioHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_portfolio_history.profolio_id
     *
     * @return the value of pm_portfolio_history.profolio_id
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    public Integer getProfolioId() {
        return profolioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_portfolio_history.profolio_id
     *
     * @param profolioId the value for pm_portfolio_history.profolio_id
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    public void setProfolioId(Integer profolioId) {
        this.profolioId = profolioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_portfolio_history.cal_date
     *
     * @return the value of pm_portfolio_history.cal_date
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    public Date getCalDate() {
        return calDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_portfolio_history.cal_date
     *
     * @param calDate the value for pm_portfolio_history.cal_date
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    public void setCalDate(Date calDate) {
        this.calDate = calDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_portfolio_history.total_assert
     *
     * @return the value of pm_portfolio_history.total_assert
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    public BigDecimal getTotalAssert() {
        return totalAssert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_portfolio_history.total_assert
     *
     * @param totalAssert the value for pm_portfolio_history.total_assert
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    public void setTotalAssert(BigDecimal totalAssert) {
        this.totalAssert = totalAssert;
    }
}