package com.citi.portfoliomanager.entity;

import java.math.BigDecimal;

public class Portfolio {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_portfolio.portfolio_id
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    private Integer portfolioId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_portfolio.name
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_portfolio.user_id
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_portfolio.intial_asset
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    private BigDecimal intialAsset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_portfolio.status
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_portfolio.cash
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    private BigDecimal cash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_portfolio.strategy
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    private Integer strategy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_portfolio.portfolio_id
     *
     * @return the value of pm_portfolio.portfolio_id
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    public Integer getPortfolioId() {
        return portfolioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_portfolio.portfolio_id
     *
     * @param portfolioId the value for pm_portfolio.portfolio_id
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    public void setPortfolioId(Integer portfolioId) {
        this.portfolioId = portfolioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_portfolio.name
     *
     * @return the value of pm_portfolio.name
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_portfolio.name
     *
     * @param name the value for pm_portfolio.name
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_portfolio.user_id
     *
     * @return the value of pm_portfolio.user_id
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_portfolio.user_id
     *
     * @param userId the value for pm_portfolio.user_id
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_portfolio.intial_asset
     *
     * @return the value of pm_portfolio.intial_asset
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    public BigDecimal getIntialAsset() {
        return intialAsset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_portfolio.intial_asset
     *
     * @param intialAsset the value for pm_portfolio.intial_asset
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    public void setIntialAsset(BigDecimal intialAsset) {
        this.intialAsset = intialAsset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_portfolio.status
     *
     * @return the value of pm_portfolio.status
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_portfolio.status
     *
     * @param status the value for pm_portfolio.status
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_portfolio.cash
     *
     * @return the value of pm_portfolio.cash
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    public BigDecimal getCash() {
        return cash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_portfolio.cash
     *
     * @param cash the value for pm_portfolio.cash
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    public void setCash(BigDecimal cash) {
        this.cash = cash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_portfolio.strategy
     *
     * @return the value of pm_portfolio.strategy
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    public Integer getStrategy() {
        return strategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_portfolio.strategy
     *
     * @param strategy the value for pm_portfolio.strategy
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    public void setStrategy(Integer strategy) {
        this.strategy = strategy;
    }
}