package com.citi.portfoliomanager.entity;

import java.math.BigDecimal;
import java.util.Date;

public class PortfolioHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_portfolio_history.portfolio_history_id
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private Integer portfolioHistoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_portfolio_history.portfolio_id
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private Integer portfolioId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_portfolio_history.cal_date
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private Date calDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_portfolio_history.total_asset
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private BigDecimal totalAsset;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_portfolio_history.portfolio_history_id
     *
     * @return the value of pm_portfolio_history.portfolio_history_id
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public Integer getPortfolioHistoryId() {
        return portfolioHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_portfolio_history.portfolio_history_id
     *
     * @param portfolioHistoryId the value for pm_portfolio_history.portfolio_history_id
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setPortfolioHistoryId(Integer portfolioHistoryId) {
        this.portfolioHistoryId = portfolioHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_portfolio_history.portfolio_id
     *
     * @return the value of pm_portfolio_history.portfolio_id
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public Integer getPortfolioId() {
        return portfolioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_portfolio_history.portfolio_id
     *
     * @param portfolioId the value for pm_portfolio_history.portfolio_id
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setPortfolioId(Integer portfolioId) {
        this.portfolioId = portfolioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_portfolio_history.cal_date
     *
     * @return the value of pm_portfolio_history.cal_date
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public Date getCalDate() {
        return calDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_portfolio_history.cal_date
     *
     * @param calDate the value for pm_portfolio_history.cal_date
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setCalDate(Date calDate) {
        this.calDate = calDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_portfolio_history.total_asset
     *
     * @return the value of pm_portfolio_history.total_asset
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public BigDecimal getTotalAsset() {
        return totalAsset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_portfolio_history.total_asset
     *
     * @param totalAsset the value for pm_portfolio_history.total_asset
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setTotalAsset(BigDecimal totalAsset) {
        this.totalAsset = totalAsset;
    }
}