package com.citi.portfoliomanager.entity;

import java.math.BigDecimal;

public class Portfolio {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_portfolio.portfolio_id
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private Integer portfolioId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_portfolio.name
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_portfolio.user_id
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_portfolio.initial_asset
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private BigDecimal initialAsset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_portfolio.status
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_portfolio.cash
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private BigDecimal cash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_portfolio.strategy
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private Integer strategy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_portfolio.portfolio_id
     *
     * @return the value of pm_portfolio.portfolio_id
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    
    private BigDecimal rateOfReturn;
    private BigDecimal totalAsset;
    
    
    
    public BigDecimal getTotalAsset() {
		return totalAsset;
	}



	public void setRateOfReturn(BigDecimal rateOfReturn) {
		this.rateOfReturn = rateOfReturn;
	}



	public void setTotalAsset(BigDecimal totalAssert) {
		this.totalAsset = totalAssert;
		this.rateOfReturn = totalAssert.subtract(initialAsset).divide(initialAsset,8,BigDecimal.ROUND_HALF_DOWN);
	}



	public BigDecimal getRateOfReturn() {
		return rateOfReturn;
	}

	

	public Integer getPortfolioId() {
        return portfolioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_portfolio.portfolio_id
     *
     * @param portfolioId the value for pm_portfolio.portfolio_id
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setPortfolioId(Integer portfolioId) {
        this.portfolioId = portfolioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_portfolio.name
     *
     * @return the value of pm_portfolio.name
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_portfolio.name
     *
     * @param name the value for pm_portfolio.name
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_portfolio.user_id
     *
     * @return the value of pm_portfolio.user_id
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_portfolio.user_id
     *
     * @param userId the value for pm_portfolio.user_id
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_portfolio.initial_asset
     *
     * @return the value of pm_portfolio.initial_asset
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public BigDecimal getInitialAsset() {
        return initialAsset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_portfolio.initial_asset
     *
     * @param initialAsset the value for pm_portfolio.initial_asset
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setInitialAsset(BigDecimal initialAsset) {
        this.initialAsset = initialAsset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_portfolio.status
     *
     * @return the value of pm_portfolio.status
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_portfolio.status
     *
     * @param status the value for pm_portfolio.status
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_portfolio.cash
     *
     * @return the value of pm_portfolio.cash
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public BigDecimal getCash() {
        return cash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_portfolio.cash
     *
     * @param cash the value for pm_portfolio.cash
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setCash(BigDecimal cash) {
        this.cash = cash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_portfolio.strategy
     *
     * @return the value of pm_portfolio.strategy
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public Integer getStrategy() {
        return strategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_portfolio.strategy
     *
     * @param strategy the value for pm_portfolio.strategy
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setStrategy(Integer strategy) {
        this.strategy = strategy;
    }
}