package com.citi.portfoliomanager.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ProductHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_product_history.product_history_id
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private Integer productHistoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_product_history.name
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_product_history.price
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_product_history.generate_date
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private Date generateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_product_history.high
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private BigDecimal high;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_product_history.low
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private BigDecimal low;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_product_history.vol
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private BigDecimal vol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_product_history.price_change
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private BigDecimal priceChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_product_history.close
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private BigDecimal close;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_product_history.type
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_product_history.open
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    private BigDecimal open;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_product_history.product_history_id
     *
     * @return the value of pm_product_history.product_history_id
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public Integer getProductHistoryId() {
        return productHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_product_history.product_history_id
     *
     * @param productHistoryId the value for pm_product_history.product_history_id
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setProductHistoryId(Integer productHistoryId) {
        this.productHistoryId = productHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_product_history.name
     *
     * @return the value of pm_product_history.name
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_product_history.name
     *
     * @param name the value for pm_product_history.name
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_product_history.price
     *
     * @return the value of pm_product_history.price
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_product_history.price
     *
     * @param price the value for pm_product_history.price
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_product_history.generate_date
     *
     * @return the value of pm_product_history.generate_date
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public Date getGenerateDate() {
        return generateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_product_history.generate_date
     *
     * @param generateDate the value for pm_product_history.generate_date
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setGenerateDate(Date generateDate) {
        this.generateDate = generateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_product_history.high
     *
     * @return the value of pm_product_history.high
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public BigDecimal getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_product_history.high
     *
     * @param high the value for pm_product_history.high
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setHigh(BigDecimal high) {
        this.high = high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_product_history.low
     *
     * @return the value of pm_product_history.low
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public BigDecimal getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_product_history.low
     *
     * @param low the value for pm_product_history.low
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setLow(BigDecimal low) {
        this.low = low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_product_history.vol
     *
     * @return the value of pm_product_history.vol
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public BigDecimal getVol() {
        return vol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_product_history.vol
     *
     * @param vol the value for pm_product_history.vol
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setVol(BigDecimal vol) {
        this.vol = vol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_product_history.price_change
     *
     * @return the value of pm_product_history.price_change
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public BigDecimal getPriceChange() {
        return priceChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_product_history.price_change
     *
     * @param priceChange the value for pm_product_history.price_change
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setPriceChange(BigDecimal priceChange) {
        this.priceChange = priceChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_product_history.close
     *
     * @return the value of pm_product_history.close
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public BigDecimal getClose() {
        return close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_product_history.close
     *
     * @param close the value for pm_product_history.close
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setClose(BigDecimal close) {
        this.close = close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_product_history.type
     *
     * @return the value of pm_product_history.type
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_product_history.type
     *
     * @param type the value for pm_product_history.type
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_product_history.open
     *
     * @return the value of pm_product_history.open
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public BigDecimal getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_product_history.open
     *
     * @param open the value for pm_product_history.open
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    public void setOpen(BigDecimal open) {
        this.open = open;
    }
}