package com.citi.portfoliomanager.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Trade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_trade.trade_id
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    private Integer tradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_trade.buy_date
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    private Date buyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_trade.buy_price
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    private BigDecimal buyPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_trade.sell_date
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    private Date sellDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_trade.sell_price
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    private BigDecimal sellPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_trade.quantity
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_trade.rate_of_return
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    private BigDecimal rateOfReturn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_trade.product_name
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_trade.portfolioId
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    private Integer portfolioid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_trade.trade_id
     *
     * @return the value of pm_trade.trade_id
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    public Integer getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_trade.trade_id
     *
     * @param tradeId the value for pm_trade.trade_id
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    public void setTradeId(Integer tradeId) {
        this.tradeId = tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_trade.buy_date
     *
     * @return the value of pm_trade.buy_date
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    public Date getBuyDate() {
        return buyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_trade.buy_date
     *
     * @param buyDate the value for pm_trade.buy_date
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    public void setBuyDate(Date buyDate) {
        this.buyDate = buyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_trade.buy_price
     *
     * @return the value of pm_trade.buy_price
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    public BigDecimal getBuyPrice() {
        return buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_trade.buy_price
     *
     * @param buyPrice the value for pm_trade.buy_price
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    public void setBuyPrice(BigDecimal buyPrice) {
        this.buyPrice = buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_trade.sell_date
     *
     * @return the value of pm_trade.sell_date
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    public Date getSellDate() {
        return sellDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_trade.sell_date
     *
     * @param sellDate the value for pm_trade.sell_date
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    public void setSellDate(Date sellDate) {
        this.sellDate = sellDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_trade.sell_price
     *
     * @return the value of pm_trade.sell_price
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    public BigDecimal getSellPrice() {
        return sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_trade.sell_price
     *
     * @param sellPrice the value for pm_trade.sell_price
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    public void setSellPrice(BigDecimal sellPrice) {
        this.sellPrice = sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_trade.quantity
     *
     * @return the value of pm_trade.quantity
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_trade.quantity
     *
     * @param quantity the value for pm_trade.quantity
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_trade.rate_of_return
     *
     * @return the value of pm_trade.rate_of_return
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    public BigDecimal getRateOfReturn() {
        return rateOfReturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_trade.rate_of_return
     *
     * @param rateOfReturn the value for pm_trade.rate_of_return
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    public void setRateOfReturn(BigDecimal rateOfReturn) {
        this.rateOfReturn = rateOfReturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_trade.product_name
     *
     * @return the value of pm_trade.product_name
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_trade.product_name
     *
     * @param productName the value for pm_trade.product_name
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_trade.portfolioId
     *
     * @return the value of pm_trade.portfolioId
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    public Integer getPortfolioid() {
        return portfolioid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_trade.portfolioId
     *
     * @param portfolioid the value for pm_trade.portfolioId
     *
     * @mbggenerated Thu Aug 16 10:19:32 CST 2018
     */
    public void setPortfolioid(Integer portfolioid) {
        this.portfolioid = portfolioid;
    }
}