package com.citi.portfoliomanager.entity;

import java.math.BigDecimal;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.user_id
     *
     * @mbggenerated Fri Aug 10 18:06:00 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.username
     *
     * @mbggenerated Fri Aug 10 18:06:00 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.password
     *
     * @mbggenerated Fri Aug 10 18:06:00 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.type
     *
     * @mbggenerated Fri Aug 10 18:06:00 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.cash
     *
     * @mbggenerated Fri Aug 10 18:06:00 CST 2018
     */
    private BigDecimal cash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.intial_asset
     *
     * @mbggenerated Fri Aug 10 18:06:00 CST 2018
     */
    private BigDecimal intialAsset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.status
     *
     * @mbggenerated Fri Aug 10 18:06:00 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.user_id
     *
     * @return the value of pm_user.user_id
     *
     * @mbggenerated Fri Aug 10 18:06:00 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.user_id
     *
     * @param userId the value for pm_user.user_id
     *
     * @mbggenerated Fri Aug 10 18:06:00 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.username
     *
     * @return the value of pm_user.username
     *
     * @mbggenerated Fri Aug 10 18:06:00 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.username
     *
     * @param username the value for pm_user.username
     *
     * @mbggenerated Fri Aug 10 18:06:00 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.password
     *
     * @return the value of pm_user.password
     *
     * @mbggenerated Fri Aug 10 18:06:00 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.password
     *
     * @param password the value for pm_user.password
     *
     * @mbggenerated Fri Aug 10 18:06:00 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.type
     *
     * @return the value of pm_user.type
     *
     * @mbggenerated Fri Aug 10 18:06:00 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.type
     *
     * @param type the value for pm_user.type
     *
     * @mbggenerated Fri Aug 10 18:06:00 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.cash
     *
     * @return the value of pm_user.cash
     *
     * @mbggenerated Fri Aug 10 18:06:00 CST 2018
     */
    public BigDecimal getCash() {
        return cash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.cash
     *
     * @param cash the value for pm_user.cash
     *
     * @mbggenerated Fri Aug 10 18:06:00 CST 2018
     */
    public void setCash(BigDecimal cash) {
        this.cash = cash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.intial_asset
     *
     * @return the value of pm_user.intial_asset
     *
     * @mbggenerated Fri Aug 10 18:06:00 CST 2018
     */
    public BigDecimal getIntialAsset() {
        return intialAsset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.intial_asset
     *
     * @param intialAsset the value for pm_user.intial_asset
     *
     * @mbggenerated Fri Aug 10 18:06:00 CST 2018
     */
    public void setIntialAsset(BigDecimal intialAsset) {
        this.intialAsset = intialAsset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.status
     *
     * @return the value of pm_user.status
     *
     * @mbggenerated Fri Aug 10 18:06:00 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.status
     *
     * @param status the value for pm_user.status
     *
     * @mbggenerated Fri Aug 10 18:06:00 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}