package com.citi.portfoliomanager.dao;

import com.citi.portfoliomanager.entity.Constant;
import com.citi.portfoliomanager.entity.ConstantExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConstantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_constant
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int countByExample(ConstantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_constant
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int deleteByExample(ConstantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_constant
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int deleteByPrimaryKey(String constantKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_constant
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int insert(Constant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_constant
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int insertSelective(Constant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_constant
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    List<Constant> selectByExample(ConstantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_constant
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    Constant selectByPrimaryKey(String constantKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_constant
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") Constant record, @Param("example") ConstantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_constant
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int updateByExample(@Param("record") Constant record, @Param("example") ConstantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_constant
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int updateByPrimaryKeySelective(Constant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_constant
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int updateByPrimaryKey(Constant record);
}