package com.citi.portfoliomanager.dao;

import com.citi.portfoliomanager.entity.PortfolioHistory;
import com.citi.portfoliomanager.entity.PortfolioHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PortfolioHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_portfolio_history
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int countByExample(PortfolioHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_portfolio_history
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int deleteByExample(PortfolioHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_portfolio_history
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int deleteByPrimaryKey(Integer portfolioHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_portfolio_history
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int insert(PortfolioHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_portfolio_history
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int insertSelective(PortfolioHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_portfolio_history
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    List<PortfolioHistory> selectByExample(PortfolioHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_portfolio_history
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    PortfolioHistory selectByPrimaryKey(Integer portfolioHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_portfolio_history
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") PortfolioHistory record, @Param("example") PortfolioHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_portfolio_history
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int updateByExample(@Param("record") PortfolioHistory record, @Param("example") PortfolioHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_portfolio_history
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int updateByPrimaryKeySelective(PortfolioHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_portfolio_history
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int updateByPrimaryKey(PortfolioHistory record);
}