package com.citi.portfoliomanager.dao;

import com.citi.portfoliomanager.entity.Position;
import com.citi.portfoliomanager.entity.PositionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_position
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    int countByExample(PositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_position
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    int deleteByExample(PositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_position
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    int deleteByPrimaryKey(Integer productProfolioId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_position
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    int insert(Position record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_position
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    int insertSelective(Position record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_position
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    List<Position> selectByExample(PositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_position
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    Position selectByPrimaryKey(Integer productProfolioId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_position
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") Position record, @Param("example") PositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_position
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    int updateByExample(@Param("record") Position record, @Param("example") PositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_position
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    int updateByPrimaryKeySelective(Position record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_position
     *
     * @mbggenerated Sun Aug 12 20:46:29 CST 2018
     */
    int updateByPrimaryKey(Position record);
}