package com.citi.portfoliomanager.dao;

import com.citi.portfoliomanager.entity.ProductHistory;
import com.citi.portfoliomanager.entity.ProductHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_history
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int countByExample(ProductHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_history
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int deleteByExample(ProductHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_history
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int deleteByPrimaryKey(Integer productHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_history
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int insert(ProductHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_history
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int insertSelective(ProductHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_history
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    List<ProductHistory> selectByExample(ProductHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_history
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    ProductHistory selectByPrimaryKey(Integer productHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_history
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProductHistory record, @Param("example") ProductHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_history
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int updateByExample(@Param("record") ProductHistory record, @Param("example") ProductHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_history
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int updateByPrimaryKeySelective(ProductHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_history
     *
     * @mbggenerated Mon Aug 13 12:02:45 CST 2018
     */
    int updateByPrimaryKey(ProductHistory record);
}