package com.citi.portfoliomanager.dao;

import com.citi.portfoliomanager.entity.Trade;
import com.citi.portfoliomanager.entity.TradeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_trade
     *
     * @mbggenerated Tue Aug 14 15:28:15 CST 2018
     */
    int countByExample(TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_trade
     *
     * @mbggenerated Tue Aug 14 15:28:15 CST 2018
     */
    int deleteByExample(TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_trade
     *
     * @mbggenerated Tue Aug 14 15:28:15 CST 2018
     */
    int deleteByPrimaryKey(Integer tradeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_trade
     *
     * @mbggenerated Tue Aug 14 15:28:15 CST 2018
     */
    int insert(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_trade
     *
     * @mbggenerated Tue Aug 14 15:28:15 CST 2018
     */
    int insertSelective(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_trade
     *
     * @mbggenerated Tue Aug 14 15:28:15 CST 2018
     */
    List<Trade> selectByExample(TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_trade
     *
     * @mbggenerated Tue Aug 14 15:28:15 CST 2018
     */
    Trade selectByPrimaryKey(Integer tradeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_trade
     *
     * @mbggenerated Tue Aug 14 15:28:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") Trade record, @Param("example") TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_trade
     *
     * @mbggenerated Tue Aug 14 15:28:15 CST 2018
     */
    int updateByExample(@Param("record") Trade record, @Param("example") TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_trade
     *
     * @mbggenerated Tue Aug 14 15:28:15 CST 2018
     */
    int updateByPrimaryKeySelective(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_trade
     *
     * @mbggenerated Tue Aug 14 15:28:15 CST 2018
     */
    int updateByPrimaryKey(Trade record);
}